---

- name: Install tmux
  apt:
    name: "{{ tmux_package }}"
    state: present

- name: Install tmux_additional_packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ tmux_additional_packages }}"
